[workspace]
members = [ "rust/add", 
    "rust/async-executor", 
    "rust/calculator", 
    "rust/crosstalk",
    "rust/crosstalk/wasm",
    "rust/infoxchange",
    "rust/infoxchange/wasm-rust",
    "rust/wasm-comp-ctx",    
    "rust/withdraw",
    ]
resolver = "2"
