[workspace]
members = [ 
    "rust/calculator", 
    "rust/crosstalk",
    "rust/crosstalk/wasm",
    "rust/infoxchange",
    "rust/infoxchange/wasm-rust",    
    "rust/withdraw",
    ]
resolver = "2"
