[package]
name = "wasm-comp-ctx"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = "32.0.0"
wasmtime-wasi = "32.0.0"  
tokio = { version = "1.44.2", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.44.2", features = ["macros"] }