[package]
name = "async-executor"
version = "0.1.0"
edition = "2024"

[features]
executor = []
tokio_executor = ["executor", "tokio"]
default = ["tokio_executor"]

[dependencies]
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"], optional = true }