package wasmexample:infoxchange;

interface id-holder {
    set-id: func( id: s32 ) -> result<_, string>;
    get-id: func() -> result<s32, string>;
}

interface worker {
    do-work: func() -> bool;
}

interface status-holder {
    enum status {
        unknown,
        offline,
        online,
    }

    set-status: func( status: status ) -> result<_, string>;
    get-status: func() -> result<status, string>;
}

world infoxchange {
    export id-holder;
    export worker;
    import status-holder;
}