package docs:adder-import-export;

interface add {
    add: func(x: u32, y: u32) -> u32;
}

interface test {
    test: func() -> bool;
}

world adder-import-export {
    export add;
    import test;
}
